
version: '3'

services: 

  app:
    build: 
      context: ./node
    container_name: app
    image: souzag32/desafio-node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - node-network
    volumes: 
       - ./node/index.js:/usr/src/app/index.js
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

  nginx:
    build: 
      context: ./nginx
    image: souzag32/nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 30s nginx -g "daemon off;"
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app


networks: 
  node-network:
    driver: bridge  